name: "StreamCinema API"
version: "0.3.11"
slug: "streamcinema"
description: "Vlastni StreamCinema backend s Webshare a Fastshare hledanim"
arch:
  - aarch64
startup: application
boot: auto
ports:
  8765/tcp: 8765
ingress: true
ingress_port: 8765
panel_icon: mdi:movie-open-play
panel_title: Stream Cinema
panel_admin: false
map:
  - config:rw
options:
  webshare_username: ""
  webshare_password: ""
  fastshare_username: ""
  fastshare_password: ""
  csfd_api_url: ""
schema:
  webshare_username: str
  webshare_password: password
  fastshare_username: str
  fastshare_password: password
  csfd_api_url: str
